modLoader="javafml"
loaderVersion="[4,)" # NeoForge loader range for 1.21.1
license="MIT"

[[mods]]
modId="mcooxidizer"                 # must match @Mod id in code
version="0.1.0"                     # whatever version you want
displayName="MCOxidizer"
authors="StyEnvy"
description='''A power-driven copper oxidizer machine that uses chips and energy to advance copper block oxidation.'''

[[dependencies.mcooxidizer]]
modId="neoforge"
type="required"
versionRange="[21,)"                # requires NeoForge 21.x
ordering="NONE"
side="BOTH"

[[dependencies.mcooxidizer]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"        # supports 1.21.1 until 1.22
ordering="NONE"
side="BOTH"
